# Video parameters
videoFolder: "./videos"
videoFilename: "0.mp4"
frameRate: 250
recTimeInSec: 6

# Camera parameters
numCams: 1
cameraSelection: [0]
cameraSettings: "C:/Code/campy-flir/campy/cameras/basler/settings/acA1920-150uc_1152x1024p_250fps_trigger_Bayer8.pfs"
cameraNames: ["Camera1"]
cameraMake: "basler"
pixelFormatInput: "bayer_bggr8"
pixelFormatOutput: "rgb0"

# Compression parameters
ffmpegLogLevel: "warning"             # "quiet", "warning", "info"
gpuID: 0                              # -1 = CPU
gpuMake: "nvidia"                     # "nvidia", "amd", "intel"                  
codec: "h264"                         # "h264", "h265", or user-defined video codec
quality: 21                           # 0-55

# Display parameters
chunkLengthInSec: 5
displayFrameRate: 10
displayDownsample: 2

# Trigger parameters (Serial Arduino control)
startArduino: 1
serialPort: "COM3"

# Other parameters
ffmpegPath: [] #["/home/usr/Documents/ffmpeg/ffmpeg"]
frameWidth: 1152
frameHeight: 1024