# Video parameters
videoFolder: "c:/campy_recordings/FOLDER"
videoFilename: "INFO_%04d.mp4" # Note overwriting
frameRate: 100
recTimeInSec: 0 # Defaults to 3 weeks
recChunkLengthInSeconds: 60

# Camera parameters
numCams: 2
cameraSelection: [0,1] # ,1,2,3]  # selects which cameras are used and in which order
cameraNames: ["SERIAL1","SERIAL2"]
# cameraSettings: "./campy/cameras/basler/settings/acA1920-150uc_1152x1024p_100fps_trigger_RGB_p6.pfs"
cameraMake: "flir"
pixelFormatInput: "gray"  # 'bayer_bggr8', 'gray', 'rgb24', 'bgr0', 'yuv420p'
pixelFormatOutput: "gray"

# FLIR camera settings (options can be checked from Spinnaker SDK, not every option is implemented!)
cameraExposureTimeInUs: 750
cameraGain: 0
bufferMode: "OldestFirst"  # First in, first out
bufferSize: 100  # 10-100. Don't set this to more than 100. Even tho the camera max is much higher, it doesn't work (probably a bug of Spinnaker)
disableGamma: False  # Gamma correction is not recommended for scientific purposes
# Compression parameters
ffmpegLogLevel: "info"   # "quiet", "warning", "info"
gpuID: [0,0] #,1] # ,0,0,0]         # -1 = CPU, GPU id for Nvidia multi-GPU, default is 0
gpuMake: "nvidia"         # "nvidia", "amd", "intel"
codec: "h264"             # "h264", "h265", or user-defined video codec
quality: 23             # 0-55
preset: "slow"

# Display parameters - note you need to remove display to use this on windows right now.
displayFrameRate: 5
displayDownsample: 4

# Other parameters
ffmpegPath: "" # "C:/FFmpeg/bin/ffmpeg.exe"
frameWidth: 1536 # max:2448, 75%:1836
frameHeight: 1536  # max:2048, 75%:1536
cameraTrigger: "None" # Start recording immediately -- this removes the need for a trigger