# Recording parameters
videoFolder: "C:/data/test/test"
recTimeInSec: 5
videoFilename: "0.mp4"

# Camera parameters
cameraMake: "basler"
numCams: 6
cameraNames: ['Camera1', 'Camera2', 'Camera3', 'Camera4','Camera5', 'Camera6']

# Compression parameters
ffmpegPath: "C:/Program Files/ffmpeg/ffmpeg-2020-09-16-git-c79f07cc0c-full_build/bin/ffmpeg"
gpuID: [0, 0, 1, 1, 1, 1]
pixelFormatInput: "rgb24" # bayer_bgg8r' # 'rgb24'
pixelFormatOutput: "rgb0"
quality: "28" # 21 35
cameraSettings: "C:/code/campy/camera_features/a2A1920-160ucBAS_40054255_10_22_2020.pfs"
frameRate: 50

# Display parameters
chunkLengthInSec: 30
displayFrameRate: 10
displayDownsample: 2

# Arduino management
startArduino: True
serialPort: "COM3"
