# Recording parameters
videoFolder: "./test"
videoFilename: "0.mp4"
frameRate: 100
recTimeInSec: 10

# Camera parameters
cameraMake: "basler"
numCams: 1
cameraSelection: [0]
cameraSettings: "./campy/cameras/basler/settings/acA1920-150uc_1152x1024p_100fps_trigger_RGB_p6.pfs"
cameraNames: ['Camera1']

# Compression parameters
ffmpegLogLevel: ["quiet"]
gpuID: -1
pixelFormatInput: "rgb24" # 'bayer_bggr8' 'rgb24'
pixelFormatOutput: "rgb0"
codec: "h264"
quality: "19"

# Display parameters
chunkLengthInSec: 30
displayFrameRate: 10
displayDownsample: 2

# Other parameters
ffmpegPath: [] #["/home/usr/Documents/ffmpeg/ffmpeg"]
emulate: False
frameWidth: 1152
frameHeight: 1024