# Recording parameters
videoFolder: "./test"
videoFilename: "0.mp4"
frameRate: 200
recTimeInSec: 5

# Camera parameters
cameraMake: "flir"
numCams: 1
cameraSelection: [0]
# cameraSettings: "./campy/cameras/basler/settings/acA1920-150uc_1152x1024p_100fps_trigger_RGB_p6.pfs"
cameraNames: ['Camera1']

# Compression parameters
ffmpegLogLevel: ["warning"]
gpuID: -1
pixelFormatInput: 'bayer_rggb8' #'bayer_bggr8' 'rgb24'
pixelFormatOutput: "rgb0"
codec: "h264"
quality: "21"

# Display parameters
chunkLengthInSec: 30
displayFrameRate: 10
displayDownsample: 2

# Other parameters
ffmpegPath: [] #["/home/usr/Documents/ffmpeg/ffmpeg"]
frameWidth: 1280 # 1152
frameHeight: 1024 # 1024