# Video parameters
videoFolder: "./test"
videoFilename: "0.mp4"
frameRate: 100
recTimeInSec: 10
emulate: False

# Camera parameters
numCams: 3
cameraSelection: [0,1,2]  # selects which cameras are used and in which order
cameraSettings: "./campy/cameras/basler/settings/acA1920-150uc_1152x1024p_100fps_trigger_RGB_p6.pfs"
# cameraSettings: "./campy/cameras/basler/settings/acA1920-150uc_1152x1024p_250fps_trigger_Bayer8.pfs"
cameraNames: ["Camera1","Camera2","Camera3"]
cameraMake: "flir"
pixelFormatInput: "rgb24" # "bayer_bggr8" "rgb24"
pixelFormatOutput: "rgb0" # "rgb0" for nvidia, "nv12" for amd/intel
frameWidth: 1152
frameHeight: 1024

# Compression parameters
ffmpegPath: [] #["/home/usr/Documents/ffmpeg/ffmpeg"]
ffmpegLogLevel: "quiet"   # "quiet", "warning", "info"; accepts string or per-stream list
gpuID: 0                  # -1 = CPU, GPU id for Nvidia multi-GPU, default is 0
gpuMake: "nvidia"         # "nvidia", "amd", "intel" # can this be automatically detected?
                          # Intel iGPU: "h264_qsv","hevc_qsv"; 
                          # Nvidia GPU: "h264_nvenc","hevc_nvenc"; on Windows or Linux
                          # AMD GPU: "h264_amf","hevc_amf" on Windows                     
codec: "h264"             # "h264", "h265" output optimized ffmpeg input params for GPU and codec
quality: "21"             # 0-55, 0 is lossless, 19-21 is visually lossless; 

# Display parameters
chunkLengthInSec: 30
displayFrameRate: 10
displayDownsample: 2