videoFolder: "./test"
camSettings: "settings.pfs"
numCams: 1
frameRate: 60
recTimeInSec: 60
gpus: [0]
cameraMake: 'Basler'
pixelFormatInput: 'rgb24'
pixelFormatOutput: 'rgb0'
quality: '21'
chunkLengthInSec: 30
displayFrameRate: 10
displayDownsample: 2