# Recording parameters
videoFolder: "./videos"
videoFilename: "0.mp4"
frameRate: 100
recTimeInSec: 30

# Camera parameters
cameraMake: "basler"
numCams: 1
cameraSelection: [0]
cameraSettings: "C:/Code/campy-flir/campy/cameras/basler/settings/acA1920-150uc_1152x1024p_100fps_trigger_RGB_p6.pfs"#
cameraNames: ['Camera1']

# Compression parameters
ffmpegLogLevel: ["warning"]
gpuID: 0
gpuMake: 'intel'
pixelFormatInput: 'rgb24' # 'bayer_bggr8'
pixelFormatOutput: "rgb0"
codec: "h264"
# quality: "0"

# Display parameters
chunkLengthInSec: 30
displayFrameRate: 10
displayDownsample: 2

# Other parameters
ffmpegPath: [] #["/home/usr/Documents/ffmpeg/ffmpeg"]
frameWidth: 1152 # 1152
frameHeight: 1024 # 1024